version: '4.30'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ../dev-config/dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      API_TOKEN: ${API_TOKEN}
      API_URL: ${API_URL}
    volumes:
      - ../frontend:/src/app
    networks:
      - strapi

  cms:
    build:
      context: ../cms
      dockerfile: ../dev-config/dockerfile.cms
    ports:
      - "1337:1337"
    environment:
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: "false"
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ../cms:/src/app
    networks:
      - strapi
    
  db:
    image: postgres:16.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - strapi

networks:
  strapi:
volumes:
  db: